version: 1.0.{build}
image: Visual Studio 2017
publish_nuget: true
pull_requests:  
  do_not_increment_build_number: true
environment:
  API_KEY:
    secure: Y0OfgaclSKT8DN0lXoZR9J0hvyTWzzqa6xsu7slKsxXAvzUCklZCpzSUpA3UguaB
  API_REFERER: apparent_build_test
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  categories:
    except:
    - RequestTest
deploy:
- provider: NuGet
  api_key:
    secure: 7KCehmZUD3npnbFKKm/YvtqA1vo3d0q1f6jy1+P9rBhnj2cJACoKNBf9cwcYZYOB
  on:
    branch: master
